### ISSUE TITLE
Image Normalization step in the Image Processing block

### ISSUE THREAD

**Issue by Mohit0928** [edgeimpulse/processing-blocks#19]
I was making the Image Classification pipeline. When I'm passing the `raw features` through the `image` processing block. I'm getting the `processed features` as normalized between `[0,1]`. I was going through the `image` processing block [code](https://github.com/edgeimpulse/processing-blocks/blob/master/image/dsp.py), but I can't find the step where the image is being normalized. Is the `image` processing block using some different code?

**Comment by Alex-EEE** [comment]
Here's where it happens: https://github.com/edgeimpulse/processing-blocks/blob/66a90b4f7c21e4534620dcaa064877b02ebd04ce/image/dsp.py#L39C12-L39C12
