### ISSUE TITLE
How x,y,z arguments need to be passed for spectral-analysis

### ISSUE THREAD

**Issue by ajithkjajith** [edgeimpulse/processing-blocks#34]
Document says :

- help='Axis data as a flattened array of x,y,z (pass as comma separated values)'

But the data needs to be sent as 

- --features= x1,y1,z1,x2,y2,z2 ......xn,yn,zn
or

- --features=x1,x2..xn,y1,y2...yn,z1,z2,...zn

**Comment by Alex-EEE** [comment]
We don't really support using these blocks from the command line, this code will be removed shortly.

Call directly in python, see an example for spectral-analysis here : https://github.com/edgeimpulse/processing-blocks/blob/master/run_spectral_analysis_via_python.py  (this file was added after this post I believe)
